input_columns:
  - order_date
  - user_id
  - order_value
segments_count:
  recency: 5  
  frequency: 5  
  monetary: 5  
rfmizer:
  look_back_period: 365 # earliest date for RFMizer (number of days)
  output_columns:
    user_id: user_id
    recency: recency
    frequency: frequency
    monetary: monetary
predictor:
  prediction_period: 182 # lookback window for RFMestimator (number of days)
output_path: .
output_file_prefix: some_unique_name
